# Continuous Random Variables and Distributions

## Exercise H1

### Part A - Pocket calculator

A pocket calculator is powered by two different batteries. It works as long as both batteries work.

* The lifetime $X$ of the battery $A$ is normally distributed with $μ_X = 30$ hours and $σ_X = 3$ hours. 
* The life $Y$ of the $B$ battery is normally distributed with $μ_Y = 35$ hours and $σ_Y = 4$ hours.

$X$ and $Y$ are independent random variables.

#### What is the probability that the $A$ battery will last between 15 and 27 hours ?

#### What is the lifetime of the $B$ battery with a probability of $85.3141$% not to be exceeded ?

#### What is the probability that the calculator will still work after 24 hours?

#### What is the probability that the lifetime of the battery $A$ is less than the lifetime of the battery $B$ ?

### Part B - Electric Component

For an electronic component, you can expect 48 failures per day (24 hours). The failures are purely random and independent of each other.

#### How is $Y$: "Time in hours between two failures" distributed (distribution and parameters)?

#### What is the probability that more than 2 hours will pass until the next failure ?

#### Using this example, verbalize the following formula:

$$\int\limits_{1}^2 2 \exp(-2y) \text{d} y$$

#### Assume that an electronic system consists of two of these components, which function independently of each other. The system fails as soon as one component stops working. What is the probability that the system will work for more than 2 hours ?

## Exercise H2

Borrowing books is very time-consuming, especially in large libraries with book magazines. So Student Bücherwurm studied the working methods of the Central Library of the TU Berlin in detail to be able to plan better.

### Part A

Most of the books in the central library cannot be taken away immediately. So Bücherwurm fills out a loan slip and throws it into the order box. He knows that the boxes are regularly emptied on the hour and the loan slips are taken to the magazine.

#### Bücherwurm throws the borrower's ticket into the box at a randomly chosen time when he is in the main building. How is the random variable $X$: "Waiting time until next emptying of the order box" distributed (distribution and parameters)?

#### On average, how long will a borrower's ticket remain in the box until it is placed in the magazine?

### Part B

It also takes time to pick out the books from the magazine. Bücherwurm assumes that the random variable $Y$: "Waiting time between emptying the box and the book arriving at the book edition" is normally distributed with a mean value of 2.5 hours and a standard deviation of 0.5 hours.

#### What is the probability that the library will take more than 3.5 hours - counted from the time the order box is emptied - until the book arrives at the output?

#### How long does Bücherwurm have to wait at the book counter after the Loan bills wait for the book on average?

### Part C

In the library administration one knows that also some borrowers lose books. During the opening hours (8 hours) an average of 6 customers report a loss.

#### How is the random variable $Z$: "Waiting time for the next customer to arrive with a lost item" distributed (distribution and parameters)?

#### On average, how many minutes elapse before the first lost customer reports a loss?

#### What is the probability that within the first three hours after the library has been opened, no customer will arrive with a lost ticket?

#### What is the probability that after a maximum of four hours the first loss is reported after no loss has been reported in the first three hours?

## Exercise H3

### Steel pins

One machine produces steel pins. Unfortunately, the diameter of the pins is subject to production-related fluctuations.

$X_1$: "Diameter of a pin" is normally distributed with $μ_1 = 6 \, \text{mm}$ and $σ_1 = 0.4 \, \text{mm}$.

#### What is the probability that the diameter of a pin deviates by more than 2% from the nominal value 6 mm?

#### What is the probability that the diameter of a pin is exactly 6 mm?

#### What value of the diameter will not be exceeded with an 85% probability?

A second machine, which operates independently of the first machine, drills holes in a workpiece into which the steel pins are to be inserted. The diameter of the drilled holes is also subject to fluctuations.

$X_2$: "Diameter of a drill hole" is normally distributed with $μ_2 = 6.05 \, \text{mm}$ and $σ_2 = 0.3 \, \text{mm}$.

#### What is the probability that the diameter of a borehole is less than 6 mm?

#### How is the random variable $Y = X_2 - X_1$ distributed (distribution and parameters)?

#### Formalize the statement: "Pen fits into the drill hole".

#### What is the probability that a pin will not fit into a drill hole?

## Exercise H4

The telephone switchboard of a fire station receives an average of 0.5 alarm messages per hour.

#### How great is the probability that during the 6-hour service time of a fire department

a) no alarm
b) at least three times alarm
c) maximum seven times alarm 

is given?

#### What is the probability that the fire department

a) gets the first alarm within the first hour of service?
b) has to wait longer than 2 hours for the first alarm?
c) has to "move out" to the first alarm in the last hour of service, of all times, after no alarm has been received in the entire 5 hour service period?

#### The chief fire chief on duty declares to his fire department team that there is a 95% probability that the first alarm will occur during the team's duty period. Does the team really have to wait less than 6 hours to receive the first alarm with 95% probability ?

## Exercise H5

### Part A

Bäcker Backfrisch also sells very fine marzipan pigs in its store.

Be $X$ : "Weight of a marzipan pig in g" normally distributed with $E(X) = 150 \, \text{g}$ and $Var(X) = 16 \, \text{g}^2$.

Max, who assumes that the weight of the individual marzipan pigs is independent of each other, goes to the store and buys 4 marzipan pigs.

Be $Y$ : "Weight of 4 marzipan pigs".

#### How is the random variable $Y$ distributed (distribution and parameters)?

#### What is the probability that the weight of the 4 marzipan pigs is exactly 600 g ?

#### What is the probability that the weight of the 4 marzipan pigs does not deviate from the expected value by more than 1% ?

### Part B

Saleswoman Mona knows from experience that during lunchtime (1 - 3 p.m.) a customer enters the store on average only every 15 minutes.

#### How is the random variable $Z_1$: "Waiting time until the next customer arrives at noon" distributed (distribution and parameters)?

#### What is the probability that Mona has to wait more than 30 minutes for the first customer during lunchtime?

Mona has been waiting 30 minutes in vain.

#### What is the probability that no customer will enter the store in the next 15 minutes?

### Part C

Mona regularly receives fresh goods every 3 hours. Unfortunately she forgot her watch today and asks her friend Leonardo for statistical advice.

#### How is the random variable $Z_2$ : "waiting time for fresh goods" distributed (distribution and parameters)?

Mona has already spent an hour talking to Leonardo without any fresh goods arriving.

#### What is the probability that Mona will receive fresh goods within the next half hour ?

## Exercise H6

Student Erwin finances his studies by taking over writing jobs.

### Part A

In the middle of his typing work, suddenly the ribbon cartridge (contents: 20 m tape) of his typewriter is empty. Fortunately, his neighbor owns a typewriter of the same design and with the same color ribbon. Since this neighbor is currently on vacation, Erwin removes the ribbon cassette from this machine unseen, installs it in his own typewriter and continues typing the started writing job.

#### What is the probability that the ribbon cassette is completely full ?

#### What is the probability that the ribbon cartridge is completely empty ?

#### What is the probability that the ribbon cassette still contains at least the 20 cm of ribbon required for the end of the writing job?

### Part B

Erwin types very correctly. On 10 lines (1.5 m ribbon) of text he calculates from experience with an average of only $\frac{3}{8}$ typos.

#### What is the expected distance between two typos?

#### What is the probability that he will not make a typo on the last 20 cm of ribbon?

#### What is the probability that the next 4 lines to be written will be free of errors, if he did not make an error in the last 4 lines written?

## Exercise H7

### Frank Furt

Frank Furt is new in Berlin. Since his financial means are limited, he cannot afford a car and has to drive with the BVG. He is toying with the idea of driving without a ticket. He has to use the subway 20 times a month. If you are caught fare dodging, you have to pay a hefty fine, buy a ticket and can then continue your journey.

The probability of being caught on any trip is 10%. The checks are carried out independently.

#### How is the random variable "number of trips per month where Frank is caught" distributed (distribution and parameters)?

#### What is the probability that Frank will be caught exactly 2 times / more than 4 times / not at all / at least 3 times, but no more than 5 times per month?

#### How often is Frank caught on average per month?

If Frank is caught, he has to pay a fine of 60 €. In addition he has to buy a ticket that costs 4 €. Since Frank wants to travel as cheaply as possible, he looks for a suitable strategy. He compares the monthly fixed costs, if he never flies off the rails, with the expected costs, if he always does.

#### Which strategy should one suggest to Frank?

#### How great should the probability be (for getting caught), so that it would not matter whether Frank always buys a ticket or always drives without paying?

### Frank's brother

Frank's brother has similar problems, but has to use the subway 60 times a month. Again, the probability of being caught on any one trip may be 10%, with checks being carried out independently.

#### How is the random variable $X$: "Number of trips per month where Frank's brother gets caught" distributed (distribution and parameters)?

#### What is the approximate probability that Frank's brother will be caught more than 2 times / at most 5 times / not at all / at least 3 times but less than 5 times per month?

#### At what level of fare will he decide to always drive without paying?

## Exercise H8

Emil Langfinger has specialized in stealing car radios. He knows from experience that there is a 50% probability that there is a car radio in a car. Langfinger goes into a parking garage at night, where there are 100 cars (random sample).

#### How is the random $X$: "Number of car radios in the parking garage" distributed (distribution and parameters)?

#### Calculate the probability that there are at most 60 car radios in the parking lot.

#### Calculate the probability that there are at least 40 car radios in the parking lot.

Langfinger knows that a security guard enters the parking lot at exactly one hour intervals to make an inspection. Langfinger enters the parking garage at any time during the night.

#### How is the random variable $Y$: "Waiting time until the guard appears" distributed (distribution and parameters)?

#### On average, how long will thieves have to wait for the guard to show up?

#### What is the probability that thieves will have to wait less than 20 minutes for the guard to appear?

#### Langfinger has already waited 30 minutes in vain for the guard to appear. What is the probability that the guard will appear within the next 20 minutes?

In order to make it harder for people like Langfinger, the manager of the parking garage decides that patrols should no longer happen exactly one hour apart. In future, the security guard will be instructed to carry out his patrols at average one-hour intervals.

#### How is the random variable $Y$: "Waiting time until the guard appears" distributed in the future regulation (distribution and parameters)?

## Exercise H9

Willi would like to spend three hours in his favourite restaurant today.

### Part A

Since he can't find a parking space, he decides to park in a no stopping zone, which is known to be illegal and is punished by the police with a fine. According to the landlord, a police patrol regularly comes by every 4 hours, which sticks a parking ticket under the windshield wipers of the wrongly parked cars.

#### How is the random variable $X$: "Waiting time until the police patrol appears" distributed (distribution and parameters)?

#### What is the probability that Willi is lucky and does not get a ticket?

After 2 hours Willi leaves the restaurant to check if there is already a ticket under the wiper of his car. Since this is not the case, he goes back into the restaurant calmly.

#### What is the probability that the police will find a ticket under the windshield wiper of his car in the remaining hour Willi spends in the restaurant?

### Part B

Willis local visit falls today exactly in the 10-hour service time of the waitress Susi. She is known for dropping only one glass (and never several glasses at the same time) during her working hours, despite the hectic pace of the restaurant.

#### What is the probability that during Willi's stay, Susi will drop 2 glasses in the first hour?

#### What is the probability that during Willi's stay, Susi will drop a glass only after two and a half hours?

#### What is the probability that no glass will be broken during Willi's stay?

Willi is already 2 hours in the restaurant without any broken glass.

#### What is the probability that Susi will drop a glass during the last hour of Willi's presence in the restaurant?

### Part C

The landlord of the restaurant wants to have fun with his guests today and has filled 5 of the 20 freshly prepared meatballs with Tabasco (a particularly hot spice). Willi has both courage and hunger for 3 meatballs, which he can choose himself.

#### What is the probability that Willi does not have to order a barrel of beer (does not eat a meatball with Tabasco)?

Willi has already eaten 2 meatballs with pleasure (and without Tabasco).

#### What is the probability that there is no Tabasco in the last meatball he chose?

## Exercise H10

### Part A

In order to check the chances of success of a new magazine "Ultra", a publisher initially sends a promotional coupon by mail to a small number of 30 randomly selected people. If the coupon is sent back to the publishing house, one receives a free sample copy of the new magazine sent. On the part of the publishing house one is rather sceptical and believes that 80% of the coupons are not sent back to the publishing house.

#### What is the probability that the third person contacted is the first to return the coupon to the publisher?

#### What is the probability that a sample copy can be sent to more than 10 / to more than 4, but less than 10 / to less than 8 of the people contacted?

Based on this verification, the publisher is convinced that the percentage of people who return such promotional coupons is actually only 20%. For the actual advertising campaign on a larger scale, the publisher now selects 10,000 people at random and sends these people one promotional coupon each.

#### What is the approximate probability that the publisher will be able to send a maximum of 1,920 sample copies / between 1,960 and 2,040 sample copies / less than 1,950 or more than 2,070 sample copies during this campaign?

The publishing house wants to provide the editor-in-chief of the new magazine with 4 assistants, which he may choose randomly from 10 people by drawing lots. Unfortunately only 6 of these 10 people have relevant experience in the newspaper industry.

#### What is the probability that none / two of the selected assistants have experience in the newspaper industry ?

## Exercise H11

## Exercise H12

## Exercise H13

## Exercise H14

### Kurfürstendamm

In Berlin, a survey is to be conducted on the population's approval of the 2032 Olympics. The institute "Info" is commissioned to develop and distribute questionnaires. The head of "Info" entrusts two of his employees (Xaver and Yvonne) with the distribution of the questionnaires: in the afternoon, when there is a heavy crowd on the Kurfürstendamm, as many questionnaires as possible are to be distributed in a certain period of time. Since Xaver and Yvonne do not want to overexert themselves in their work, they choose the following different procedures: Xaver regularly picks a person every 10 minutes to hand out a questionnaire to. Yvonne on the other hand distributes an average of 6 sheets per hour in irregular intervals.

#### How is the random variable $X$: "Waiting time until Xaver distributes a questionnaire" distributed (distribution and parameters)?

#### How is the random variable Y: "Waiting time until distribution of a questionnaire by Yvonne" distributed (distribution and parameters)?

The boss comes to Kurfürstendamm in the afternoon at any time to secretly watch his employees at work.

#### On average, how long will he have to wait until he can observe the distribution of a questionnaire by Xaver?

####What is the probability that he will not have to wait longer than 5 minutes until he can observe the distribution of a questionnaire by Xaver/by Yvonne?

#### The boss has already waited 10 minutes without Yvonne having distributed a questionnaire during this time. What is the probability that he does not have to wait more than another 10 minutes for the distribution of a questionnaire by Yvonne?

The boss decides to send another employee (Zorro) to the Kurfürstendamm to support Xaver and Yvonne. However, since Zorro loves dogs and women, he only distributes questionnaires to women accompanied by a dog. One can assume that in the afternoon on Kurfürstendamm the waiting time for a woman accompanied by a dog is normally distributed ($\mu = 12$, $\sigma = 4$ minutes).

#### What is the probability that Zorro has to wait less than 8 minutes for a woman with a dog to come by?

#### Zorro wants to finish in 10 minutes but still wants to get rid of his last questionnaire. What are the chances that he has to take his last questionnaire home?

## Exercise H15

In a factory there are two machines.

### Part A

Machine A produces special drums for highly toxic chemicals. The diameter of a drum in cm ($X_A$) is a normally distributed random variable:

$$X_A \, \text{ist} \, N(\mu_A, {\sigma_A}^2) \sim N(50, 4)$$

Due to the highly toxic chemicals, the drums are attached to special holder during transport, which allow a deviation of only $\pm$ 1 cm from the standard diameter.

#### What is the probability that a drum will fit into such a holder?

#### What is the probability that a drum has exactly the standard diameter?

#### What is the probability that the diameter of drum is less than 49 cm?

### Part B

Machine B produces lids for these drums independently of machine A. The diameter of a lid in cm ($X_B$) is a normally distributed random variable:

$$X_B \, \text{ist} \, N(\mu_B, {\sigma_B}^2) \sim N(53, 5)$$

To ensure that the barrels are hermetically sealed, the diameter of a lid must not be smaller than the diameter of a barrel.

#### What is the probability that toxic gases can escape from a closed drum?

#### What is the probability that a barrel and its lid have the same diameter?

### Part C

In order for a lid to match a barrel as closely as possible, each barrel with its lid must pass through two checks. The control time in minutes of controller $K_1$ for a barrel with lid ($Y_1$) is a constantly evenly distributed random variable:

$$Y_1 \, \text{is continuously equally distributed in} \, \[a; b\] \sim \[1; 7\]$$

After the $K_1$ check is completed, a second check is performed independently by the $K_2$ checker. The control time in minutes of controller $K_2$ for a barrel with lid ($Y_2$) is an exponentially distributed random variable:
$$Y_2 \, \text{ist} \, Exp(\lambda) \sim Exp(1)$$
#### Determine the expected value and the variance for the entire control time for one barrel (with lid).

#### What is the probability that the total control time for a barrel will be at least 2 minutes but no more than 8 minutes?

49 barrels with lids are produced per day and pass through the control process independently.

#### What is the probability that the total control for such a daily production takes more than 3 hours and 37 minutes?

## Exercise H16

In my restaurant strange conditions prevail. There is only one cook and only one waiter. The waiter comes to the table regularly every 15 minutes to take the guests' wishes. He writes down each guest's meal request on a separate slip of paper. Once the order is taken, the waiter throws these slips of paper into a box. The cook then randomly pulls a note out of the box, cooks and serves the meal. The ordered food arrives at the guest in completely irregular intervals (on average 15 minutes after the order).

Be
* $X$: "Waiting time until the waiter appears".
* $Y$: "Number of meals served per minute
* $Z$: "Waiting time until the food is served (time between ordering and serving)".

#### How is the random variable $X$ distributed (distribution and parameters)?

#### How is the random variable $Y$ distributed (distribution and parameters)?

#### How is the random variable $Z$ distributed (distribution and parameters)?

#### On average, how long will you have to wait for the waiter to show up?

#### Let's assume that you have been waiting 10 minutes in vain for the waiter. What is the probability that you can finally order your food within the next 2 minutes?

#### Let's assume that the order has finally been placed. What is the probability that after exactly 15 minutes the food will be served?

#### Let's assume that the order has finally been placed. What is the probability that you will have to wait less than 15 minutes for your meal?

#### Let's say you have ordered your food and you have waited more than 15 minutes in vain for your meal. What is the probability that after another 5 minutes you are still sitting at the table hungry?

#### Exactly 30 minutes after you enter the restaurant and sit at the table, you have an appointment with your parents in front of the restaurant. What is the probability that your parents will not have to wait for you if the waiter has taken your order after 5 minutes and you need 5 minutes to eat your meal?

#### Let's assume that you went to this restaurant with your parents to eat. On average, how much time would have passed before the food was ordered and everyone was served their meal?

#### How does the result of 10. change if the "waiting time until food is served" would be normally distributed with $\mu = 15$ minutes and $\sigma^2 = 25$ minutes?

## Exercise H17

### Part A

Student Statistix takes the bus or a cab to the university at about the same time every day. Because of his upcoming statistics exam he is so excited today that he did not take his watch with him. Arriving at the bus stop he remembers that the bus leaves regularly every 20 minutes. Cabs, on the other hand, pass this place without any rules, but at this time of day the average waiting time for such an event is 15 minutes. Furthermore one can assume that cabs and buses do not influence each other in their driving behavior.

#### What is the probability that Statistix has to wait exactly 13 minutes for the bus today?

#### What is the probability that Statistix has to wait 5 minutes for a ride today?

#### What would be the average number of passing cabs if the probability of waiting more than 12 minutes for a cab was 25%?

#### What is the probability that the bus will arrive at the bus stop 15 minutes after Statistix has arrived at the bus stop and that within these 15 minutes not a single cab drives past?

#### At what time interval would the bus have to leave if the probability of waiting for the bus for more than 4 minutes is exactly 60%?

Assume that the waiting time for a cab passing by is normally distributed with an expectation value of 18 minutes at a standard deviation of 2 minutes.

#### What is the probability of having to wait more than 16 minutes but less than 24 minutes for a cab?

### Part B

Let the random variable $X$ be continuously uniform distributed in $\[a; b\]$. Show with the help of a formal proof that $E(X) = \frac{a + b}{2}$.
